# Lecture 10 — NumPy, Part 1


<a id="lecture-10-numpy-part-1"></a>

<div align="center" style="  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);  border-radius: 16px;  padding: 30px 25px 20px;  box-shadow: 0 8px 32px rgba(31, 38, 135, 0.37);  margin-bottom: 20px;  position: relative;  overflow: hidden;"><div style="  position: absolute; top: 0; left: 0; right: 0; bottom: 0;  background: radial-gradient(circle at 20% 50%, rgba(255,255,255,0.1) 0%, transparent 50%),              radial-gradient(circle at 80% 20%, rgba(255,255,255,0.08) 0%, transparent 40%);  pointer-events: none;"></div><div style="position: relative; z-index: 1;"><p style="color: rgba(255,255,255,0.9); font-size: 0.85em; letter-spacing: 3px; text-transform: uppercase; margin-bottom: 5px; font-family: 'Segoe UI', sans-serif;">Lecture 10 of 18 — Progress: 56%</p><span style="display:inline-block;width:10px;height:10px;border-radius:50%;background:#4CAF50;margin:0 3px;"></span><span style="display:inline-block;width:10px;height:10px;border-radius:50%;background:#4CAF50;margin:0 3px;"></span><span style="display:inline-block;width:10px;height:10px;border-radius:50%;background:#4CAF50;margin:0 3px;"></span><span style="display:inline-block;width:10px;height:10px;border-radius:50%;background:#4CAF50;margin:0 3px;"></span><span style="display:inline-block;width:10px;height:10px;border-radius:50%;background:#4CAF50;margin:0 3px;"></span><span style="display:inline-block;width:10px;height:10px;border-radius:50%;background:#4CAF50;margin:0 3px;"></span><span style="display:inline-block;width:10px;height:10px;border-radius:50%;background:#4CAF50;margin:0 3px;"></span><span style="display:inline-block;width:10px;height:10px;border-radius:50%;background:#4CAF50;margin:0 3px;"></span><span style="display:inline-block;width:10px;height:10px;border-radius:50%;background:#4CAF50;margin:0 3px;"></span><span style="display:inline-block;width:10px;height:10px;border-radius:50%;background:#4CAF50;margin:0 3px;"></span><span style="display:inline-block;width:10px;height:10px;border-radius:50%;background:#FFD700;margin:0 3px;"></span><span style="display:inline-block;width:10px;height:10px;border-radius:50%;background:rgba(255,255,255,0.25);margin:0 3px;"></span><span style="display:inline-block;width:10px;height:10px;border-radius:50%;background:rgba(255,255,255,0.25);margin:0 3px;"></span><span style="display:inline-block;width:10px;height:10px;border-radius:50%;background:rgba(255,255,255,0.25);margin:0 3px;"></span><span style="display:inline-block;width:10px;height:10px;border-radius:50%;background:rgba(255,255,255,0.25);margin:0 3px;"></span><span style="display:inline-block;width:10px;height:10px;border-radius:50%;background:rgba(255,255,255,0.25);margin:0 3px;"></span><span style="display:inline-block;width:10px;height:10px;border-radius:50%;background:rgba(255,255,255,0.25);margin:0 3px;"></span><span style="display:inline-block;width:10px;height:10px;border-radius:50%;background:rgba(255,255,255,0.25);margin:0 3px;"></span><h1 style="color: #ffffff; font-size: 2.2em; margin: 15px 0 5px; text-shadow: 2px 2px 8px rgba(0,0,0,0.3); font-family: 'Segoe UI', sans-serif;">PyPro-SCiDaS</h1><p style="color: rgba(255,255,255,0.85); font-size: 1.05em; margin: 5px 0 15px; font-family: 'Segoe UI', sans-serif;">An Initiation to Programming using Python (Init2Py)</p><div style="  background: rgba(255,255,255,0.12);  backdrop-filter: blur(10px);  border: 1px solid rgba(255,255,255,0.2);  border-radius: 12px;  padding: 15px 20px;  display: inline-block;  margin: 10px 0;"><h2 style="color: #ffffff; font-size: 1.4em; margin: 0; text-shadow: 1px 1px 4px rgba(0,0,0,0.2); font-family: 'Segoe UI', sans-serif;">📊 Lecture 10 — NumPy — Part 1</h2></div><p style="color: #ffffff; font-size: 0.8em; margin: 15px 0 0; font-family: 'Segoe UI', sans-serif;">Python Proficiency for Scientific Computing and Data Science</p><div style="background: rgba(255,255,255,0.18); backdrop-filter: blur(10px); -webkit-backdrop-filter: blur(10px); border: 1px solid rgba(255,255,255,0.25); border-radius: 10px; padding: 12px 20px; margin: 15px auto 5px; display: inline-block; text-align: center;">
<table style="margin: 0 auto; border-collapse: collapse;">
<tr>
<td style="padding: 5px 15px; color: rgba(0,0,0,0.9); font-size: 0.9em; border-right: 1px solid rgba(0,0,0,0.15);">🧑‍🏫 Instructor: <strong style="color:#000;">Yaé Gaba</strong></td>
<td style="padding: 5px 15px; color: rgba(0,0,0,0.9); font-size: 0.9em; border-right: 1px solid rgba(0,0,0,0.15);">📘 Course: <strong style="color:#000;">Init2Py</strong></td>
<td style="padding: 5px 15px; color: rgba(0,0,0,0.9); font-size: 0.9em; border-right: 1px solid rgba(0,0,0,0.15);">📅 Date: <strong style="color:#000;">October 2025</strong></td>
<td style="padding: 5px 15px; color: rgba(0,0,0,0.9); font-size: 0.9em; border-right: 1px solid rgba(0,0,0,0.15);">🎓 Semester: <strong style="color:#000;">Semester 1, 2025–2026</strong></td>
<td style="padding: 5px 15px; color: rgba(0,0,0,0.9); font-size: 0.9em; border-right: 1px solid rgba(0,0,0,0.15);">⏱️ Estimated: <strong style="color:#000;">60 min</strong></td>
<td style="padding: 5px 15px; font-size: 0.9em;"><span style="background: #BF360A; color: #fff; padding: 2px 10px; border-radius: 12px; font-size: 0.85em; font-weight: 600;">Intermediate</span></td>
</tr>
<tr>
<td colspan="4" style="padding: 8px 15px 3px; color: rgba(0,0,0,0.9); font-size: 0.85em; text-align: center; border-top: 1px solid rgba(0,0,0,0.1);">🏛️ <a href="https://airina-labs.github.io/AIRINA-Labs/" target="_blank" style="color:#000; text-decoration: none;"><strong>AI Research and Innovation Nexus for Africa (AIRINA Labs)</strong></a>, AI.Technipreneurs, Bénin<br>&amp; <a href="https://acas-yde.org/" target="_blank" style="color:#000; text-decoration: none;"><strong>African Center for Advanced Studies (ACAS)</strong></a>, Cameroon</td>
</tr>
<tr>
<td colspan="4" style="padding: 3px 15px 2px; color: rgba(0,0,0,0.9); font-size: 0.8em; text-align: center;">✉️ <a href="mailto:yaeulrich.gaba@gmail.com" style="color: #1a237e; text-decoration: none;">yaeulrich.gaba@gmail.com</a>   |   🔗 <a href="https://www.linkedin.com/in/gabayae/" target="_blank" style="color: #0077B5; text-decoration: none;">LinkedIn</a>   |   🌐 <a href="https://gabayae.github.io/" target="_blank" style="color: #667eea; text-decoration: none;">Website</a></td>
</tr>
</table>
</div></div></div>

<div style="text-align: right; margin: -10px 0 10px;"><a href="https://ai-technipreneurs.github.io/python_website/notebooks/index.html" style="  color: #667eea;  text-decoration: none;  font-size: 0.85em;  font-family: 'Segoe UI', sans-serif;  padding: 4px 12px;  border: 1px solid #667eea;  border-radius: 20px;">📚 Course Index</a></div>

<div style="
  background: linear-gradient(135deg, #e8f5e9 0%, #f1f8e9 100%);
  border-left: 5px solid #4CAF50;
  border-radius: 0 12px 12px 0;
  padding: 20px 25px;
  margin: 15px 0;
  box-shadow: 0 2px 8px rgba(0,0,0,0.06);
  font-family: 'Segoe UI', sans-serif;
">

<h3 style="color: #2E7D32; margin-top: 0; font-size: 1.2em;">
🎯 Learning Objectives
</h3>

<p style="color: #555; font-size: 0.95em; margin-bottom: 10px;">
By the end of this lecture, you will be able to:
</p>

<ul style="list-style-type: none; padding-left: 5px; font-size: 0.95em;">
    <li style="margin: 8px 0; color: #424242; line-height: 1.5;">✅ Understand why NumPy is the foundation of scientific Python</li>
    <li style="margin: 8px 0; color: #424242; line-height: 1.5;">✅ Create arrays from lists and with <code>arange</code>, <code>linspace</code>, <code>zeros</code>, <code>ones</code></li>
    <li style="margin: 8px 0; color: #424242; line-height: 1.5;">✅ Access and modify array elements with indexing and slicing</li>
    <li style="margin: 8px 0; color: #424242; line-height: 1.5;">✅ Reshape and restructure arrays</li>
    <li style="margin: 8px 0; color: #424242; line-height: 1.5;">✅ Use fancy indexing and boolean masks</li>
</ul>

</div>

<div class="transition-bridge" style="background: transparent; border-left: 3px solid #b0bec5; padding: 10px 18px; margin: 20px 0 10px; color: #546e7a; font-size: 0.95em; font-style: italic; font-family: 'Segoe UI', sans-serif;">
What happens when you try to operate on arrays of <strong>different shapes</strong>? NumPy's broadcasting rules handle this elegantly.
</div>

<a id="table-of-contents"></a>

<div style="background: linear-gradient(135deg, #e3f2fd 0%, #e8eaf6 100%); border-left: 5px solid #667eea; border-radius: 0 12px 12px 0; padding: 18px 22px; margin: 15px 0; box-shadow: 0 2px 8px rgba(0,0,0,0.06); font-family: Segoe UI, sans-serif;">
<h3 style="color: #1a237e; margin-top: 0; font-size: 1.1em;">📑 Table of Contents</h3>
<ul style="list-style-type: none; padding-left: 5px; margin: 0;">
<li style="margin: 4px 0; padding-left: 0px; color: #424242; font-size: 0.9em;"><a href="#lecture-10-numpy-part-1" style="color: #424242; text-decoration: none;">● 📊 Lecture 10 — NumPy — Part 1</a></li>
<li style="margin: 4px 0; padding-left: 0px; color: #424242; font-size: 0.9em;"><a href="#what-is-numpy" style="color: #424242; text-decoration: none;">1. ● What is NumPy?</a></li>
<li style="margin: 4px 0; padding-left: 0px; color: #424242; font-size: 0.9em;"><a href="#numpy-arrays" style="color: #424242; text-decoration: none;">2. ● NumPy arrays</a></li>
<li style="margin: 4px 0; padding-left: 15px; color: #424242; font-size: 0.9em;"><a href="#to-use-numpy-you-need-to-import-the-module" style="color: #424242; text-decoration: none;">3. ▸ To use numpy you need to import the module</a></li>
<li style="margin: 4px 0; padding-left: 15px; color: #424242; font-size: 0.9em;"><a href="#from-lists" style="color: #424242; text-decoration: none;">4. ▸ From lists</a></li>
<li style="margin: 4px 0; padding-left: 15px; color: #424242; font-size: 0.9em;"><a href="#understanding-the-code" style="color: #424242; text-decoration: none;">5. ▸ 🧠 Understanding the Code</a></li>
<li style="margin: 4px 0; padding-left: 15px; color: #424242; font-size: 0.9em;"><a href="#step-by-step-explanation" style="color: #424242; text-decoration: none;">6. ▸ 🔍 Step-by-Step Explanation</a></li>
<li style="margin: 4px 0; padding-left: 15px; color: #424242; font-size: 0.9em;"><a href="#numpy-also-provides-many-functions-to-create-arrays" style="color: #424242; text-decoration: none;">7. ▸ Numpy also provides many functions to create arrays:</a></li>
<li style="margin: 4px 0; padding-left: 15px; color: #424242; font-size: 0.9em;"><a href="#numpy-array-attributes" style="color: #424242; text-decoration: none;">8. ▸ NumPy Array Attributes</a></li>
<li style="margin: 4px 0; padding-left: 15px; color: #424242; font-size: 0.9em;"><a href="#basic-data-types" style="color: #424242; text-decoration: none;">9. ▸ Basic data types</a></li>
<li style="margin: 4px 0; padding-left: 0px; color: #424242; font-size: 0.9em;"><a href="#array-indexing-accessing-elements-subarrays" style="color: #424242; text-decoration: none;">10. ● Array Indexing: Accessing Elements/Subarrays</a></li>
<li style="margin: 4px 0; padding-left: 15px; color: #424242; font-size: 0.9em;"><a href="#reshaping-of-arrays" style="color: #424242; text-decoration: none;">11. ▸ Reshaping of Arrays</a></li>
<li style="margin: 4px 0; padding-left: 15px; color: #424242; font-size: 0.9em;"><a href="#fancy-indexing" style="color: #424242; text-decoration: none;">12. ▸ Fancy indexing</a></li>
<li style="margin: 4px 0; padding-left: 15px; color: #424242; font-size: 0.9em;"><a href="#exercise" style="color: #424242; text-decoration: none;">13. ▸ Exercise:</a></li>
<li style="margin: 4px 0; padding-left: 0px; color: #424242; font-size: 0.9em;"><a href="#array-math" style="color: #424242; text-decoration: none;">14. ● Array math</a></li>
<li style="margin: 4px 0; padding-left: 0px; color: #424242; font-size: 0.9em;"><a href="#vectorizing-functions" style="color: #424242; text-decoration: none;">15. ● Vectorizing functions</a></li>
<li style="margin: 4px 0; padding-left: 0px; color: #424242; font-size: 0.9em;"><a href="#broadcasting" style="color: #424242; text-decoration: none;">16. ● Broadcasting</a></li>
<li style="margin: 4px 0; padding-left: 15px; color: #424242; font-size: 0.9em;"><a href="#key-takeaways" style="color: #424242; text-decoration: none;">17. ▸ 🎯 Key Takeaways</a></li>
</ul>
</div>

<div style="background: linear-gradient(135deg, #ede7f6 0%, #e8eaf6 100%); border-left: 5px solid #7E57C2; border-radius: 0 12px 12px 0; padding: 18px 22px; margin: 15px 0; box-shadow: 0 2px 8px rgba(0,0,0,0.06); font-family: 'Segoe UI', sans-serif;">
<h3 style="color: #4527A0; margin-top: 0; font-size: 1.1em;">🔗 Building on What You Know</h3>
<p style="color: #424242; font-size: 0.95em; line-height: 1.6; margin: 0;">You've learned Python's built-in data structures (lists, dicts) and control flow (loops, functions). Now we enter the world of <strong>scientific computing</strong>. NumPy replaces Python lists with high-performance arrays that are the foundation of every data science library you'll use — Pandas, Matplotlib, Scikit-learn, and more.</p>
</div>

<div style="background: linear-gradient(135deg, #fff8e1 0%, #fff3e0 100%); border-left: 5px solid #FF9800; border-radius: 0 12px 12px 0; padding: 18px 22px; margin: 15px 0; box-shadow: 0 2px 8px rgba(0,0,0,0.06); font-family: 'Segoe UI', sans-serif;">
<h3 style="color: #E65100; margin-top: 0; font-size: 1.1em;">🌍 Real-World Scenario</h3>
<p style="color: #424242; font-size: 0.95em; line-height: 1.6; margin-bottom: 10px;">You have satellite imagery data: a 1000×1000 grid of pixel brightness values. Using a Python list of lists, applying a brightness filter takes <strong>12 seconds</strong>. Using a NumPy array, the same operation takes <strong>0.05 seconds</strong> — that's a 240× speedup.</p><p style="color: #424242; font-size: 0.95em; line-height: 1.6;">NumPy is the foundation of scientific Python. It replaces slow Python loops with fast, vectorized C-level operations on multi-dimensional arrays. Every data science library (Pandas, Matplotlib, Scikit-learn) is built on top of it.</p>
</div>

[The NumPy Reference](https://docs.scipy.org/doc/numpy/reference/).

<div style="text-align: right; margin-top: 12px; font-size: 0.85em;"><a href="#table-of-contents" style="color: #667eea; text-decoration: none;">↑ Back to TOC</a></div>

<a id="what-is-numpy"></a>

## What is NumPy?


> **NumPy (Numerical Python)** is the core library for scientific computing in Python, that provide high-performance vector, matrix, and higher-dimensional data structures for Python. It is implemented in ``C`` and ``Fortran``. so when calculations are vectorized (formulated with vectors and matrices), the performance is very good. It provides a high-performance multidimensional array object, and tools for working with these arrays.


> This library can be used for different functions in **Linear algebra, Matrix computations, Fourier Transforms**. Alongside Numpy is most suitable for performing basic numerical computations such as *mean, median, range*, etc.

> It is an open source module of Python which provides fast mathematical computation on arrays and matrices. Since, arrays and matrices are an essential part of the Machine Learning ecosystem.

> ``Machine learning`` uses vectors, and in that regard, Numpy can be used in all common classes of problem in Machine Learning. Example: **Classification, Regressoin, Clustering** etc.




<div style="text-align: right; margin-top: 12px; font-size: 0.85em;"><a href="#table-of-contents" style="color: #667eea; text-decoration: none;">↑ Back to TOC</a></div>

<a id="numpy-arrays"></a>

## NumPy arrays

At the core of the NumPy package, is the ``ndarray`` object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance.

  
  
  A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the *rank* of the array; the *shape* of an array is a tuple of integers giving the size of the array along each dimension.
  
  
  
Data manipulation in Python is nearly synonymous with NumPy array manipulation: even newer tools like Pandas are built around the NumPy array. This section will present several examples of using NumPy array manipulation to access data and subarrays, and to split, reshape, and join the arrays.   


There are a number of ways to initialize new numpy arrays, for example from:

* a Python list or tuples;
* using functions that are dedicated to generating numpy arrays, such as arange, linspace, etc.;
* reading data from files.

<div style="text-align: right; margin-top: 12px; font-size: 0.85em;"><a href="#table-of-contents" style="color: #667eea; text-decoration: none;">↑ Back to TOC</a></div>

<a id="to-use-numpy-you-need-to-import-the-module"></a>

### To use numpy you need to import the module

**Import conventions** : The recommended convention to import numpy is:

In [1]:
# Import the numpy library
import numpy as np


<div style="text-align: right; margin-top: 12px; font-size: 0.85em;"><a href="#table-of-contents" style="color: #667eea; text-decoration: none;">↑ Back to TOC</a></div>

<a id="from-lists"></a>

### From lists
For example, to create new vector and matrix arrays from Python lists we can use the ``np.array`` function.

In [16]:
# a vector: the argument to the array function is a Python list
v = np.array([2.51,98.2,3.34,4.92])
v

array([ 2.51, 98.2 ,  3.34,  4.92])

In [3]:
# Check the variable type
type(v)

numpy.ndarray

In [23]:
a = np.array([1.7, 2.5, 0.3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"


<class 'numpy.ndarray'>
(3,)


In [12]:
?a.shape


Type:        tuple
String form: (3,)
Length:      1
Docstring:  
Built-in immutable sequence.

If no argument is given, the constructor returns an empty tuple.
If iterable is specified the tuple is initialized from iterable's items.

If the argument is a tuple, the return value is the same object.

<div style="text-align: right; margin-top: 12px; font-size: 0.85em;"><a href="#table-of-contents" style="color: #667eea; text-decoration: none;">↑ Back to TOC</a></div>

<a id="step-by-step-explanation"></a>

<a id="understanding-the-code"></a>


### 🧠 Understanding the Code

```python
import numpy as np

a = np.array([1.7, 2.5, 0.3])   # Create a rank-1 NumPy array
print(type(a))                  # Prints the data type of the object
print(a.shape)                  # Prints the shape (dimensions) of the array
```

---

### 🔍 Step-by-Step Explanation

1. **`import numpy as np`**
   This imports the **NumPy** library, a powerful tool for numerical computations in Python, and gives it the alias `np`.

2. **`a = np.array([1.7, 2.5, 0.3])`**
   This creates a **NumPy array** from a Python list `[1.7, 2.5, 0.3]`.

   * The array contains **three elements** (floating-point numbers).
   * Since all elements are in a single bracket `[ ... ]`, it is a **1-dimensional** array (or **rank-1** array).

3. **`print(type(a))`**
   This prints the **type** of the variable `a`.

   **Output:**

   ```
   <class 'numpy.ndarray'>
   ```

   🧩 **Explanation:**
   This confirms that `a` is a NumPy array object, not a regular Python list.

4. **`print(a.shape)`**
   The `.shape` attribute returns the **dimensions (shape)** of the array as a tuple.

   **Output:**

   ```
   (3,)
   ```

   🧩 **Explanation:**
   The array has **one dimension** with **3 elements**.

   * The **`3`** means there are three values.
   * The **comma** indicates it’s a 1-dimensional tuple.

---

### ✅ **Summary of the Output**

| **Command** | **Output**                | **Meaning**                   |
| ----------- | ------------------------- | ----------------------------- |
| `type(a)`   | `<class 'numpy.ndarray'>` | Confirms `a` is a NumPy array |
| `a.shape`   | `(3,)`                    | A 1D array with 3 elements    |

---


```


In [17]:
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

5.0 2.5 0.3
[5.  2.5 0.3]


In [18]:
b = np.array([[1.2,2.3,3.4],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"


(2, 3)
1 2 4


<div style="text-align: right; margin-top: 12px; font-size: 0.85em;"><a href="#table-of-contents" style="color: #667eea; text-decoration: none;">↑ Back to TOC</a></div>

<a id="numpy-also-provides-many-functions-to-create-arrays"></a>

### Numpy also provides many functions to create arrays:

In [20]:
import numpy as np


print("-----------------------------------------------------------------------")

print("Evenly spaced: \n")

a1 = np.arange(10) # 0 .. n-1  (!). Evenly spaced.
print(a1)

print("\n")

b1 = np.arange(1, 9, 2) # start, end (exclusive), step.
print(b1)


print("=========================================================================")

print("Spaced by number of points: \n")


c1 = np.linspace(0, 1, 6)   # start, end, num-points
print(c1)


print("\n")

d1 = np.linspace(0, 1, 5, endpoint=False)
print(d1)



print("=========================================================================")
print("Common arrays: \n")


a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"
print("\n")

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

print("\n")

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"
print("\n")

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"
print("\n")

e = np.random.random((2,2))  # Create an array filled with random values
print("E=",e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

-----------------------------------------------------------------------
Evenly spaced: 

[0 1 2 3 4 5 6 7 8 9]


[1 3 5 7]
Spaced by number of points: 

[0.  0.2 0.4 0.6 0.8 1. ]


[0.  0.2 0.4 0.6 0.8]
Common arrays: 

[[0. 0.]
 [0. 0.]]


[[1. 1.]]


[[7 7]
 [7 7]]


[[1. 0.]
 [0. 1.]]


E= [[0.08360895 0.72610431]
 [0.51335217 0.31084629]]


You can read about other methods of array creation [in the documentation](https://docs.scipy.org/doc/numpy/user/basics.creation.html#arrays-creation).

* * * *
Exercise: **Creating arrays using functions**

> Experiment with `arange`, `linspace`, `ones`, `zeros`, `eye` and `diag`.
    Create different kinds of arrays with random numbers.
    Try setting the seed before creating an array with random values.
    Look at the function `np.empty`. What does it do? When might this be useful?

* * * *

<div style="text-align: right; margin-top: 12px; font-size: 0.85em;"><a href="#table-of-contents" style="color: #667eea; text-decoration: none;">↑ Back to TOC</a></div>

<a id="numpy-array-attributes"></a>

### NumPy Array Attributes

Each array has attributes ``ndim`` (the number of dimensions), ``shape`` (the size of each dimension), and ``size`` (the total size of the array):

In [2]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array


In [22]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)


x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


<div style="text-align: right; margin-top: 12px; font-size: 0.85em;"><a href="#table-of-contents" style="color: #667eea; text-decoration: none;">↑ Back to TOC</a></div>

<a id="basic-data-types"></a>

### Basic data types

Different data-types allow us to store data more compactly in memory, but most of the time we simply work with floating point numbers. Note that, in the example above, NumPy auto-detects the data-type from the input.

In [ ]:
a = np.array([1, 2, 3])
print(a.dtype)


b = np.array([1., 2., 3.])
print(b.dtype)


In [ ]:
You can explicitly specify which data-type you want:

In [ ]:
c = np.array([1, 2, 3], dtype=float)
print(c.dtype)

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is a more example:

In [ ]:
import numpy as np

x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"


You can read all about numpy datatypes [in the documentation](https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

<div class="transition-bridge" style="background: transparent; border-left: 3px solid #b0bec5; padding: 10px 18px; margin: 20px 0 10px; color: #546e7a; font-size: 0.95em; font-style: italic; font-family: 'Segoe UI', sans-serif;">
Now that we can create arrays, we need to <strong>access specific elements</strong> and sub-arrays. NumPy's indexing is powerful and flexible.
</div>

<div style="text-align: right; margin-top: 12px; font-size: 0.85em;"><a href="#table-of-contents" style="color: #667eea; text-decoration: none;">↑ Back to TOC</a></div>

<a id="array-indexing-accessing-elements-subarrays"></a>

## Array Indexing: Accessing Elements/Subarrays


Numpy offers several ways to index into arrays.

**Slicing**: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:



In [ ]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

print(a)

print('--------------------------------------------------------------------------')

print(b)

print('--------------------------------------------------------------------------')


# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"

print('--------------------------------------------------------------------------')

b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array.

In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"

print('--------------------------------------------------------------------------')


print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"

print('--------------------------------------------------------------------------')

print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"


<div style="text-align: right; margin-top: 12px; font-size: 0.85em;"><a href="#table-of-contents" style="color: #667eea; text-decoration: none;">↑ Back to TOC</a></div>

<a id="reshaping-of-arrays"></a>

### Reshaping of Arrays

Another useful type of operation is reshaping of arrays. The most flexible way of doing this is with the ``reshape`` method. For example, if you want to put the numbers 1 through 9 in a $3 \times 3$ grid, you can do the following:

In [ ]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

Note that for this to work, the size of the initial array must match the size of the reshaped array. Tyr a few examples that you will create.

<div style="text-align: right; margin-top: 12px; font-size: 0.85em;"><a href="#table-of-contents" style="color: #667eea; text-decoration: none;">↑ Back to TOC</a></div>

<a id="fancy-indexing"></a>

### Fancy indexing

Fancy indexing is the name for when an array or a list is used in-place of an index:

In [ ]:
twenty = (np.arange(4 * 5)).reshape(4, 5)
twenty

In [ ]:
row_indices = [1, 2, 3]
twenty[row_indices]

In [ ]:
col_indices = [1, 2, -1] # remember, index -1 means the last element
twenty[row_indices, col_indices]

We can also use index **masks**:

    If the index mask is a NumPy array of data type bool, then an element is selected (True) or not (False) depending on the value of the index mask at the position of each element



In [ ]:
# 1D array of random integers
# get 10 integers from 0 to 23

num_samples = 10
integers = np.random.randint(23, size=num_samples)
integers

In [ ]:
# mask has to be of the same shape as the array to be indexed; else IndexError would be thrown
# mask for indexing alternate elements in the array
row_mask = np.array([True, False, True, False, True, False, True, False, True, False])

integers[row_mask]



This feature is very useful to conditionally select elements from an array, using for example comparison operators:


In [ ]:
range_arr = np.arange(0, 10, 0.5)
range_arr

In [ ]:
mask = (range_arr > 5) * (range_arr < 7.5)
mask
# What is happenning here?

In [ ]:
# Access elements by index
range_arr[mask]


<div style="text-align: right; margin-top: 12px; font-size: 0.85em;"><a href="#table-of-contents" style="color: #667eea; text-decoration: none;">↑ Back to TOC</a></div>

<a id="exercise"></a>

* * * *
### Exercise:
 > Investigate the **Concatenation, Splitting, Copies,repeat, tile, vstack, hstack**  functions for numpy arrays.

 > Investigate [Views versus copies in NumPy](https://scipy-cookbook.readthedocs.io/items/ViewsVsCopies.html)



* * * *

<div class="transition-bridge" style="background: transparent; border-left: 3px solid #b0bec5; padding: 10px 18px; margin: 20px 0 10px; color: #546e7a; font-size: 0.95em; font-style: italic; font-family: 'Segoe UI', sans-serif;">
With arrays created and elements accessible, let's put them to work: <strong>mathematical operations</strong> are where NumPy truly shines.
</div>

<div style="text-align: right; margin-top: 12px; font-size: 0.85em;"><a href="#table-of-contents" style="color: #667eea; text-decoration: none;">↑ Back to TOC</a></div>

<a id="array-math"></a>

## Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [3]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))


[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


We instead use the ``dot`` function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. ``dot`` is available both as a function in the numpy module and as an instance method of array objects:

In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))


Numpy provides many useful functions for performing computations on arrays; one of the most useful is ``sum``

In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"


You can find the full list of mathematical functions provided by numpy [in the documentation](https://docs.scipy.org/doc/numpy/reference/routines.math.html).

<div class="transition-bridge" style="background: transparent; border-left: 3px solid #b0bec5; padding: 10px 18px; margin: 20px 0 10px; color: #546e7a; font-size: 0.95em; font-style: italic; font-family: 'Segoe UI', sans-serif;">
What if you have a custom Python function and want it to run on every element of an array? <strong>Vectorization</strong> makes this fast.
</div>

<div style="text-align: right; margin-top: 12px; font-size: 0.85em;"><a href="#table-of-contents" style="color: #667eea; text-decoration: none;">↑ Back to TOC</a></div>

<a id="vectorizing-functions"></a>

## Vectorizing functions

As mentioned several times by now, to get good performance we should always try to avoid looping over elements in our vectors and matrices, and instead use vectorized algorithms. The first step in converting a scalar algorithm to a vectorized algorithm is to make sure that the functions we write work with vector inputs.

In [ ]:
# Define the Theta() function
def Theta(x):
    """
    scalar implementation of the Heaviside step function.
    """
    if x >= 0:
        return 1
    else:
        return 0

In [ ]:
v1 = np.array([-3,-2,-1,0,1,2,3])

Theta(v1)



That didn't work because we didn't write the function Theta so that it can handle a vector input...

To get a vectorized version of Theta we can use the Numpy function vectorize. In many cases it can automatically vectorize a function:


In [ ]:
Theta_vec = np.vectorize(Theta)
Theta_vec(v1)

On the Other Hand (OTHO), we can also implement the function to accept a vector input from the beginning (requires more effort but might give better performance):

In [ ]:
# Define the Theta() function
def Theta(x):
    """
    Vector-aware implementation of the Heaviside step function.
    """
    return 1 * (x >= 0)

In [ ]:
Theta(v1)

In [ ]:
# it even works with scalar input
Theta(-1.2), Theta(2.6)

Numpy provides many more functions for manipulating arrays; you can see the full list [in the documentation](https://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html).

<div style="text-align: right; margin-top: 12px; font-size: 0.85em;"><a href="#table-of-contents" style="color: #667eea; text-decoration: none;">↑ Back to TOC</a></div>

<a id="broadcasting"></a>

## Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)


This works; however when the matrix ``x`` is very large, computing an explicit loop in Python could be slow. Note that adding the vector ``v ``to each row of the matrix ``x`` is equivalent to forming a matrix ``vv`` by stacking multiple copies of ``v`` vertically, then performing elementwise summation of ``x`` and ``vv``. We could implement this approach like this:

In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                 # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
y = x + vv  # Add x and vv elementwise
print(y)  # Prints "[[ 2  2  4
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"


Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"


The line ``y = x + v`` works even though ``x`` has shape **(4, 3)** and ``v`` has shape **(3,)** due to broadcasting; this line works as if ``v`` actually had shape **(4, 3)**, where each row was a copy of ``v``, and the sum was performed elementwise.

* * * *

Broadcasting two arrays together follows these rules:


1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.

2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
    
3. The arrays can be broadcast together if they are compatible in all dimensions.
    
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
    
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension


If this explanation does not make sense, try reading the explanation from the [documentation](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)
Functions that support broadcasting are known as universal functions. You can find the list of all universal functions [in the documentation](https://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

In [ ]:
Here are some applications of broadcasting:

In [ ]:
import numpy as np

# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(x + v)

# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)


Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.

<div style="text-align: right; margin-top: 12px; font-size: 0.85em;"><a href="#table-of-contents" style="color: #667eea; text-decoration: none;">↑ Back to TOC</a></div>

<a id="key-takeaways"></a>

<div style="background: linear-gradient(135deg, #e8f5e9 0%, #f1f8e9 100%); border-left: 5px solid #4CAF50; border-radius: 0 12px 12px 0; padding: 20px 25px; margin: 25px 0 15px; box-shadow: 0 2px 8px rgba(0,0,0,0.06); font-family: 'Segoe UI', sans-serif;">
<h3 style="color: #2E7D32; margin-top: 0; font-size: 1.2em;">🎯 Key Takeaways</h3>
<ul style="list-style-type: none; padding-left: 5px;">
<li style="margin: 8px 0; color: #424242; font-size: 0.95em; line-height: 1.5;">NumPy provides the <code>ndarray</code> — a fast, memory-efficient multi-dimensional array.</li>
<li style="margin: 8px 0; color: #424242; font-size: 0.95em; line-height: 1.5;">Create arrays with <code>np.array()</code>, <code>np.zeros()</code>, <code>np.ones()</code>, <code>np.arange()</code>, <code>np.linspace()</code>.</li>
<li style="margin: 8px 0; color: #424242; font-size: 0.95em; line-height: 1.5;">Indexing and slicing work like lists but extend to multiple dimensions: <code>a[row, col]</code>.</li>
<li style="margin: 8px 0; color: #424242; font-size: 0.95em; line-height: 1.5;">Vectorized operations replace slow Python loops with fast element-wise computations.</li>
<li style="margin: 8px 0; color: #424242; font-size: 0.95em; line-height: 1.5;">Broadcasting allows operations between arrays of different shapes without explicit looping.</li>
</ul>
</div>

<div style="text-align: right; margin-top: 12px; font-size: 0.85em;"><a href="#table-of-contents" style="color: #667eea; text-decoration: none;">↑ Back to TOC</a></div>

---<div align="center" style="  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);  border-radius: 16px;  padding: 25px;  margin-top: 30px;  box-shadow: 0 8px 32px rgba(31, 38, 135, 0.25);  font-family: 'Segoe UI', sans-serif;  position: relative;  overflow: hidden;"><div style="  position: absolute; top: 0; left: 0; right: 0; bottom: 0;  background: radial-gradient(circle at 80% 50%, rgba(255,255,255,0.08) 0%, transparent 50%);  pointer-events: none;"></div><div style="position: relative; z-index: 1; background: rgba(255,255,255,0.18); backdrop-filter: blur(10px); -webkit-backdrop-filter: blur(10px); border: 1px solid rgba(255,255,255,0.25); border-radius: 10px; padding: 15px 20px; margin: 0 auto; display: inline-block;"><h2 style="color: #000; margin: 0 0 5px; font-size: 1.4em; text-shadow: none;">🏁 End of Lecture 10 — NumPy — Part 1</h2><p style="color: rgba(0,0,0,0.6); font-size: 0.9em; margin: 5px 0 15px;">PyPro-SCiDaS • Python Proficiency for Scientific Computing and Data Science</p><div style="background: rgba(255,255,255,0.2); border-radius: 10px; height: 12px; width: 80%; margin: 10px auto; overflow: hidden;"><div style="background: linear-gradient(90deg, #4CAF50, #8BC34A); height: 100%; width: 61%; border-radius: 10px;"></div></div><p style="color: rgba(0,0,0,0.55); font-size: 0.75em; margin: 3px 0 15px;">Course progress: 61% complete (11 of 18 lectures)</p><p style="color: rgba(0,0,0,0.5); font-size: 0.7em; margin: 10px 0 0;">© 2025 Yaé Gaba — <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" style="color: rgba(0,0,0,0.6); text-decoration: underline;">CC BY-NC 4.0</a></p></div></div><div style="  background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);  border-radius: 0 0 16px 16px;  padding: 15px 20px;  margin-top: -5px;  box-shadow: 0 4px 12px rgba(0,0,0,0.08);  font-family: 'Segoe UI', sans-serif;"><table style="width: 100%; border-collapse: collapse;"><tr><td style="padding: 10px; width: 45%;"><a href="https://ai-technipreneurs.github.io/python_website/notebooks/09-errors-debugging.html" style="text-decoration: none;"><span style="color: #888; font-size: 0.8em;">← Previous</span><br><span style="color: #1565C0; font-weight: 600;">🐛 Lecture 9: Errors and Debugging</span></a></td><td style="text-align: center; width: 10%;"><a href="https://ai-technipreneurs.github.io/python_website/notebooks/index.html" style="text-decoration: none; font-size: 1.5em; color: #667eea;" title="Course Index">📚</a></td><td style="padding: 10px; text-align: right; width: 45%;"><a href="https://ai-technipreneurs.github.io/python_website/notebooks/11-numpy-2.html" style="text-decoration: none;"><span style="color: #888; font-size: 0.8em;">Next →</span><br><span style="color: #1565C0; font-weight: 600;">📊 Lecture 11: NumPy — Part 2</span></a></td></tr></table></div>---